apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: argocheck
  name: argocheck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocheck
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: argocheck
    spec:
      containers:
      - image: priya20xenonstack/drupal-latest:8
        name: argo-test
        resources: {}
status: {}
